repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: .*\.(json|lock)$
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8 --ignore=W503
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy --strict
        types: [python]
